name = "mivoy"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

# Define KV namespace
kv_namespaces = [
  { binding = "PROPERTIES_KV", id = "633473f72f9c444ca81d0413d340d3c0" }
]