name = "trademe-property-tracker"
main = "src/index.ts"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]
node_compat = true

[vars]
# Define your environment variables here
API_BASE_URL = "https://api.trademe.co.nz/v1"
TRADEME_BASE_URL = "https://www.trademe.co.nz"
SUPABASE_STORAGE_BUCKET = "property-images"
TRADEME_CONSUMER_KEY = "05853D50C9B49D0BBF512C4F7C288098"
TRADEME_CONSUMER_SECRET = "EE038BB9632A0BB6E1A6637555067E24"
TRADEME_SANDBOX_MODE = "true"  # Set to "false" for production

# Development environment
[env.dev]
vars = { 
  ENVIRONMENT = "development", 
  SCRAPE_INTERVAL_HOURS = "24",
  TRADEME_SANDBOX_MODE = "true"
}

# Production environment
[env.production]
vars = { 
  ENVIRONMENT = "production", 
  SCRAPE_INTERVAL_HOURS = "24",
  TRADEME_SANDBOX_MODE = "false"
}

# Trigger for scheduled scraping job
[triggers]
crons = ["0 15 * * *"] # 3:00 AM NZT (15:00 UTC)

# KV Namespace for storing property data
[[kv_namespaces]]
binding = "PROPERTIES_KV"
id = "your-kv-namespace-id-here"
preview_id = "your-preview-kv-namespace-id-here"

# Secrets (add these using wrangler secret put)
# SUPABASE_URL
# SUPABASE_ANON_KEY

# Add site configuration for frontend deployment
[site]
bucket = "../dist"
entry-point = "."

# Build configuration
[build]
command = "cd .. && npm run build"
